# Site settings
title: Formula 49
email: your-email@domain.com
description: "49cc speed formula"
baseurl: ""
url: "http://formula-49.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
